dataset: cifar10
model: WRN28
drop_rate: 0.5
pretrained: False
batch_size: 128
device: "cuda:0"
optimizer: adamw
weight_decay: 1.e-6
random_seed: 2
epochs: 100
learning_rate: 1.e-3
lr_scheduler: multisteplr
steplr_milestones: [30, 60, 90]
steplr_gamma: 0.1
frequency_save: 999
save_folder: record/attack/ftrojan/bd_cifar10_WRN28
attack: ftrojan
channel_list: [1,2]
magnitude: 30
YUV: True
window_size: 32
pos_list: [[31, 31], [15, 15]]
attack_label_trans: all2one  # all2all, all2one
attack_target: 2
pratio: 0.1
clean_label_attack: False